### ISSUE TITLE
Hello, can you show the usage of highlighting

### ISSUE THREAD

**Issue by ykmx** [kimheonseung/elasticsearch8#1]

**Comment by kimheonseung** [comment]
sorry for replying.
I'll consider it :->

**Comment by kimheonseung** [comment]
I commit some basic highlight code.
Please check [this commit.](https://github.com/kimheonseung/elasticsearch8/commit/5faac870f0d61ed24b71e79f1046d59721f60b92)

I use highlight query on keyword field which is suitable for term query.
Highlight request and result shows like this.
[request]
{
  "highlight": true,
  "highlightField": [ "originalLog" ],
  "highlightKeyword": [ "hello" ],
  ...
}

[result]
{
  "highlight": {
    "originalLog": [
      ".. some text... **pretag** hello **posttag** ... some other text..."
    ]
  },
  ...
}
